repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: fix-byte-order-marker
    -   id: check-docstring-first
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: requirements-txt-fixer

# Lint restructured text documentation.
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

# CPPCheck is a useful static linter for detecting bugs.
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: cppcheck
        args: [--language=c++, --library=googletest]

# CPPLint is useful for checking code styling and conventions.
-   repo: https://github.com/cpplint/cpplint
    rev: 1.6.1
    hooks:
    -   id: cpplint
        args: [--root=src]

# Project Code formatter for CPP source.
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
    -   id: clang-format
        args: [--style=Google]

# Hooks to verify Arduino Library conventions
-   repo: https://github.com/CreatingNull/arduino-hooks
    # Note for the pre-commit GitHub workflow this executable must be added.
    rev: v0.3.0
    hooks:
    -   id: arduino-lint
        args: [--fail-on-warn, --library-manager=update]
