name: build

on:

  push:
    branches:
      - main
    paths-ignore:
      - '.docs/**'
      - '.tests/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Localise artifacts
        run: |
          mkdir NullPacketComms/
          cp README.md NullPacketComms/
          cp LICENSE.md NullPacketComms/
          cp keywords.txt NullPacketComms/
          cp library.properties NullPacketComms/
          cp src/NullPacketComms.cpp NullPacketComms/
          cp src/NullPacketComms.h NullPacketComms/

      - name: Create zip of artifacts
        uses: edgarrc/action-7z@v1.0.5
        with:
          args: 7z a -y -tzip -mx9 NullPacketComms.zip ./NullPacketComms/

      -  name: Check Build on Example Compiles
         env:
           ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL: true
         run: |
           curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 0.32.2
           bin/arduino-cli core update-index
           bin/arduino-cli core install arduino:avr
           bin/arduino-cli lib install --zip-path NullPacketComms.zip
           bin/arduino-cli --fqbn arduino:avr:nano compile examples/simple_example.ino

      - name: Upload the Build
        uses: actions/upload-artifact@v3
        with:
          name: null-packet-comms-artifacts
          path: NullPacketComms.zip
