name: build

on:

  push:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          cp README.md src/NullPacketComms/
          cp LICENSE.md src/NullPacketComms/

      - uses: edgarrc/action-7z@v1.0.5
        with:
          args: 7z a -y -tzip -mx9 NullPacketComms.zip src/NullPacketComms/

      - uses: actions/upload-artifact@v2
        with:
          name: null-packet-comms-artifacts
          path: NullPacketComms.zip
