name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:

  pre-commit:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install LLVM Toolchain
      uses: KyleMayes/install-llvm-action@v1.5.0
      with:
        version: "13.0"

    - name: Install Python
      uses: actions/setup-python@v2

    - name: Install System Dependancies
      run: |
        pip install --upgrade pip wheel cpplint
        sudo apt-get update -y
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-lint/main/etc/install.sh | sh -s 1.2.0
        echo "${PWD}/bin/" >> $GITHUB_PATH

    - name: Run Pre-Commit
      uses: pre-commit/action@v2.0.3
