name: build

on:

  push:
    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Localise artifacts
        run: |
          cp README.md src/NullPacketComms/
          cp LICENSE.md src/NullPacketComms/
          cp keywords.txt src/NullPacketComms/
          cp library.properties src/NullPacketComms/

      - name: Create zip of artifacts
        uses: edgarrc/action-7z@v1.0.5
        with:
          args: 7z a -y -tzip -mx9 NullPacketComms.zip ./src/NullPacketComms/

      - name: Upload the Build
        uses: actions/upload-artifact@v2
        with:
          name: null-packet-comms-artifacts
          path: NullPacketComms.zip

      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v2.7.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
