name: build

on:

  push:
    branches:
      - main
    paths-ignore:
      - '.docs/**'
      - '.tests/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Localise artifacts
        run: |
          mkdir NullPacketComms/
          cp README.md NullPacketComms/
          cp LICENSE.md NullPacketComms/
          cp keywords.txt NullPacketComms/
          cp library.properties NullPacketComms/
          cp src/NullPacketComms.cpp NullPacketComms/
          cp src/NullPacketComms.h NullPacketComms/

      - name: Create zip of artifacts
        uses: edgarrc/action-7z@v1.0.5
        with:
          args: 7z a -y -tzip -mx9 NullPacketComms.zip ./NullPacketComms/

      - name: Upload the Build
        uses: actions/upload-artifact@v3
        with:
          name: null-packet-comms-artifacts
          path: NullPacketComms.zip
